"""统一 Prompt 管理（ChatPromptTemplate）。"""

from lc.prompts._all import (
    IMAGE_EXTRACT_CHAT_PROMPT,
    IMAGE_EXTRACT_PROMPT,
    JUDGE_CHAT_PROMPT,
    JUDGE_SYSTEM_PROMPT,
    JUDGE_USER_PROMPT,
    MEMORY_AGENT_SECTION_HEADER,
    MEMORY_QA_CHAT_PROMPT,
    MEMORY_QA_SYSTEM_PROMPT,
    MEMORY_QA_USER_PROMPT,
    RAG_CHAT_PROMPT,
    RAG_SYSTEM_PROMPT,
    RAG_USER_PROMPT,
    REACT_CHAT_PROMPT,
    REACT_SYSTEM_PROMPT,
    build_judge_messages,
    build_memory_messages,
    build_memory_system_section,
    build_rag_messages,
    build_react_messages,
    get_image_extract_prompt,
    render_chat_prompt,
)

__all__ = [
    "REACT_SYSTEM_PROMPT",
    "REACT_CHAT_PROMPT",
    "RAG_SYSTEM_PROMPT",
    "RAG_CHAT_PROMPT",
    "RAG_USER_PROMPT",
    "MEMORY_QA_SYSTEM_PROMPT",
    "MEMORY_QA_CHAT_PROMPT",
    "MEMORY_QA_USER_PROMPT",
    "MEMORY_AGENT_SECTION_HEADER",
    "JUDGE_SYSTEM_PROMPT",
    "JUDGE_USER_PROMPT",
    "JUDGE_CHAT_PROMPT",
    "IMAGE_EXTRACT_PROMPT",
    "IMAGE_EXTRACT_CHAT_PROMPT",
    "build_react_messages",
    "build_rag_messages",
    "build_memory_messages",
    "build_memory_system_section",
    "build_judge_messages",
    "get_image_extract_prompt",
    "render_chat_prompt",
]
